-- ServiceDesk Lite — local seed data.
--
-- Intentionally empty of accounts and tickets at this stage:
--
--   * Real users are created through Supabase Auth (signup or the
--     Dashboard), which is what fires public.handle_new_user() and gives
--     them a profile — inserting rows into auth.users by hand here would
--     be an unstable, undocumented shortcut that easily drifts from
--     whatever auth.users actually requires release to release.
--   * Tickets always reference an author_id -> profiles(id), so no ticket
--     can be seeded without a real profile to attach it to.
--   * Promoting a profile to 'admin' is a deliberately separate, controlled
--     operation for the next stage (authentication) — not something this
--     seed script does. It will not be done via raw_user_meta_data or
--     app_metadata; public.handle_new_user() ignores both on purpose.
--
-- This file is safe to run repeatedly (idempotent no-op) via
-- `supabase db reset`. Once real users exist locally, an admin can be
-- assigned with, for example:
--
--   UPDATE public.profiles SET role = 'admin' WHERE id = '<uuid-of-user>';
--
-- run directly against the local database — not through this file, and
-- never against a production project.

-- No rows inserted in this stage.
